services:
  backend:
    build:
      context: ./trailerflix-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://admin:Admin123@cluster0.avnrdjf.mongodb.net/trailerflix?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build:
      context: ./trailerflix-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
