apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailerflix-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: trailerflix-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: "mongodb+srv://admin:Admin123@cluster0.avnrdjf.mongodb.net/trailerflix?retryWrites=true&w=majority&appName=Cluster0"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: trailerflix-backend
spec:
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
