apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailerflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: trailerflix-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_API_URL
              value: "http://trailerflix-backend:5001"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trailerflix-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
