# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: trailerflix-frontend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: frontend
#           image: trailerflix-frontend:latest
#           imagePullPolicy: IfNotPresent
#           env:
#             - name: REACT_APP_API_URL
#               value: "http://trailerflix-backend:5001"
#           ports:
#             - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: trailerflix-frontend
# spec:
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30080
#   type: NodePort

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trailerflix-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: arkhalid/trailerflix-frontend:dev-latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_URL
              # inside k8s, "trailerflix-backend" resolves to the backend Service in this same namespace
              value: "http://trailerflix-backend:5001"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: trailerflix-frontend
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30080
