name: Deploy Trailerflix Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # For a remote cluster: set up kubeconfig
      # - name: Configure kubeconfig
      #   run: |
      #     echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/backend.yaml
          kubectl apply -f k8s/frontend.yaml
