# name: Deploy Trailerflix Infra

# on:
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 1️⃣ checkout infra (manifests + workflow)
#       - name: Checkout infra repo
#         uses: actions/checkout@v3

#       # 2️⃣ checkout the backend code
#       - name: Checkout backend repo
#         uses: actions/checkout@v3
#         with:
#           repository: ARK2712/trailerflix-backend
#           ref: dev
#           path: trailerflix-backend
#           # if private: token: ${{ secrets.GITHUB_TOKEN }}

#       # 3️⃣ checkout the frontend code
#       - name: Checkout frontend repo
#         uses: actions/checkout@v3
#         with:
#           repository: ARK2712/trailerflix-frontend
#           ref: dev
#           path: trailerflix-frontend

#       # 4️⃣ Azure login
#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       # 5️⃣ set AKS context
#       - name: Set AKS context
#         uses: azure/aks-set-context@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           resource-group: trailerflix-rg
#           cluster-name: trailerflix-aks

#       # 6️⃣ Docker Hub login
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # 7️⃣ Build & push backend
#       - name: Build & push backend image
#         run: |
#           docker build \
#             -t arkhalid/trailerflix-backend:dev-latest \
#             ./trailerflix-backend
#           docker push arkhalid/trailerflix-backend:dev-latest

#       # 8️⃣ Build & push frontend
#       - name: Build & push frontend image
#         run: |
#           docker build \
#             -t arkhalid/trailerflix-frontend:dev-latest \
#             ./trailerflix-frontend
#           docker push arkhalid/trailerflix-frontend:dev-latest

#       # 9️⃣ Deploy to AKS
#       - name: Apply Kubernetes manifests
#         run: |
#           kubectl apply -f k8s/namespaces.yaml --validate=false
#           kubectl apply -f k8s/backend.yaml    --validate=false
#           kubectl apply -f k8s/frontend.yaml   --validate=false

name: Deploy Trailerflix Infra

# on:
#   workflow_run:
#     workflows:
#       - Build & Push Backend Image
#       - Build & Push Frontend Image
#     types:
#       - completed
on:
  repository_dispatch:
    types: [dev-push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ checkout infra (manifests + workflow)
      - name: Checkout infra repo
        uses: actions/checkout@v3

      # 2️⃣ Azure login (uses the AZURE_CREDENTIALS secret you added)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Configure kubectl to talk to your AKS cluster
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: trailerflix-rg
          cluster-name: trailerflix-aks

      # 4️⃣ log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build & push backend image
      - name: Build & push backend image
        run: |
          docker build \
            -t arkhalid/trailerflix-backend:dev-latest \
            ./trailerflix-backend
          docker push arkhalid/trailerflix-backend:dev-latest

      # 6️⃣ Build & push frontend image
      - name: Build & push frontend image
        run: |
          docker build \
            -t arkhalid/trailerflix-frontend:dev-latest \
            ./trailerflix-frontend
          docker push arkhalid/trailerflix-frontend:dev-latest

      # 7️⃣ Apply your Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespaces.yaml --validate=false
          kubectl apply -f k8s/backend.yaml    --validate=false
          kubectl apply -f k8s/frontend.yaml   --validate=false
